[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd indexer && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd indexer && npm run build"
]

[start]
cmd = "cd indexer && npm start"
